const ACTION_TYPES = {
  //USERS_SAGA
  GET_USERS_ACTION: 'GET_USERS_ACTION', // Saga
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  // CREATE:
  CREATE_USER_ACTION: 'CREATE_USER_ACTION', // Saga
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',
  // DELETE:
  DELETE_USER_ACTION: 'DELETE_USER_ACTION', // Saga
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',
};

export default ACTION_TYPES;
